#!/bin/bash

# Pandora FMS WMI Server, startup script
# Sancho Lerena, <slerena@gmail.com>
# Linux Version (generic)
# 2.0 Build 080620

# Configurable path and filenames
PANDORA_HOME="/etc/pandora/pandora_server.conf"
PANDORA_PID_PATH="/var/run"
PANDORA_PID=$PANDORA_PID_PATH/pandora_wmi.pid
PANDORA_DAEMON=/usr/bin/pandora_wmi

# Main script

if [ ! -d "$PANDORA_PID_PATH" ]
then
	echo "Pandora FMS WMI Server cannot write it's PID file in $PANDORA_PID_PATH. Please create that directory"
	exit
fi

if [ ! -f $PANDORA_DAEMON ] 
then
        echo "Pandora FMS WMI Server not found, please check setup and read manual"
        exit
fi

case "$1" in
  start)
	OLD_PATH="`pwd`"
	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
        if [ ! -z $PANDORA_PID ]
	then
		echo "Pandora FMS WMI Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
		exit 1
	fi
	
	$PANDORA_DAEMON $PANDORA_HOME -D
	sleep 1

	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
        if [ ! -z "$PANDORA_PID" ]
	then
		echo "Pandora FMS WMI Server is now running with PID $PANDORA_PID"
	else
		echo "Cannot start Pandora FMS WMI Server. Aborted."
	fi
	cd "$OLD_PATH"
        ;;
  stop)
	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
        if [ -z $PANDORA_PID ]
	then
		echo "Pandora FMS WMI Server is not running, cannot stop it."
		exit 1	
	else
	   	echo "Stopping Pandora FMS WMI Server"
           	kill $PANDORA_PID > /dev/null 2>&1
           	rm -f $PANDORA_PID
	fi
        ;;
  force-reload|restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: pandora_plugin {start|stop|restart}"
        exit 1
esac

