#!/usr/bin/ksh

# Pandora FMS AIX Agent, startup script
# Copyright (c) 2006-2009 Artica ST, <info@artica.es>
# v1.3.1 Build 091104
# http://www.pandorafms.com


# DONT USE WITH OPENSSH
# DOESNT WORK WHEN MAKES A CALL THAT USE @ CHARACTER
# USE DIRECTLY PANDORA AGENT SCRIPT

# for example: pandora_agent /usr/share/pandora_agent/ &
 
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
PANDORA_PATH=/usr/share/pandora_agent/
DAEMON=pandora_agent
PIDFILE=/var/locks/pandora_agent.pid


if [ ! -f $PANDORA_PATH/$DAEMON ]
then
	echo "Pandora Agent not found at $PANDORA_PATH/$DAEMON, please check setup"
	exit
fi

case "$1" in
  start)
        if [ -f $PIDFILE ]
        then
                echo "Pandora Agent is currently running on this machine. Aborting now..."
                exit
        fi
	nohup $PANDORA_PATH/$DAEMON $PANDORA_PATH >> $PANDORA_PATH/pandora.log &  MYPID=$!
        echo $MYPID > $PIDFILE
	#MYPID=`ps -Alf | grep $DAEMON | grep -v grep | awk '{ print $4 }' | tail -1`
	echo $MYPID > $PIDFILE
	echo "Pandora Agent is now running with PID $MYPID"
        ;;
  stop)
        if [ -f $PIDFILE ]
        then
   	echo "Stopping Pandora Agent."
	   PID_2=`cat $PIDFILE`
           if [ ! -z "`ps -f -p $PID_2 | grep -v grep | grep 'pandora_agent'`" ]
           then
   	   	kill -9 `cat $PIDFILE`
	   fi
	   rm -f $PIDFILE 
        else
           echo "Pandora Agent is not running, cannot stop it. Aborting now..."
        fi
        ;;
  force-reload|restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: /etc/init.d/pandora_agent {start|stop|restart|force-reload}"
        exit 1
esac

