pref("pandora.ip_address","http://firefly.artica.es/pandora_demo" );
pref("pandora.api_pass","doreik0");
pref("pandora.user_name","demo");
pref("pandora.pass", "demo");
pref("pandora.critical",11);
pref("pandora.informational",1);
pref("pandora.maintenance",10);
pref("pandora.normal",6);
pref("pandora.warning",2);
pref("pandora.events",20);
pref("pandora.refresh",10);
pref("pandora.new_events",0);
pref("pandora.sound_alert",true);
pref("pandora.changed", false);
pref("pandora.data_check", true);
pref("pandora.firstLoad", true);
pref("pandora.data", null);