#!/bin/sh
# Script de arranque de Agente Pandora
# Sancho Lerena, <slerena@gmail.com>
# Version para Linux (generico)
# v1.0.3 

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
PANDORA_PATH=/usr/share/pandora_agent_sim
DAEMON=pandora_agent_sim.sh
PIDFILE=/var/run/pandora_sim.pid
test -x $PANDORA_PATH/$DAEMON || exit

case "$1" in
  start)
        if [ -f $PIDFILE ]
        then
                echo "Pandora Agent SIM is currently running on this machine. Aborting now..."
                exit
        fi
        $PANDORA_PATH/$DAEMON $PANDORA_PATH >> $PANDORA_PATH/pandora.log &  MYPID=$!
        echo $MYPID > $PIDFILE 
	echo "Pandora Agent is now running with PID $MYPID"
        ;;
  stop)
        if [ -f $PIDFILE ]
        then
           echo "Stopping Pandora Agent SIM."
	   kill -9 `cat $PIDFILE`   
	   rm -f $PIDFILE 
        else
           echo "Pandora Agent SIM is not running, cannot stop it. Aborting now..."
        fi
        ;;
  force-reload|restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Uso: /etc/init.d/pandora_agent {start|stop|restart|force-reload}"
        exit 1
esac

