<?php
// Pandora - The Free Monitoring System
// This code is protected by GPL license.
// Este codigo esta protegido por la licencia GPL.
// Sancho Lerena <slerena@gmail.com>, 2003-2006
// Raul Mateos <raulofpandora@gmail.com>, 2004-2006
?>
<html>
<head>
<title>Pandora - The Free Monitoring System Help - II. Users</title>
<link rel="stylesheet" href="../../include/styles/pandora.css" type="text/css">
<style>
div.logo {float:left;}
div.toc {padding-left: 200px;}
div.rayah {clear:both; border-top: 1px solid #708090; width: 100%;}
</style>
</head>

<body>
<div class='logo'>
<img src="../../images/logo_menu.gif" alt='logo'><h1>Pandora Help v1.2</h1>
</div>
<div class="toc">
<h1><a href="chap1.php">1. Introduction</a> « <a href="toc.php">Table of Contents</a> » <a href="chap3.php">3. Agents</a></h1>

</div>
<div class="rayah">
<p align='right'>Pandora is a GPL Software Project. &copy; Sancho Lerena 2003-2005, David villanueva 2004-2005, Alex Arnal 2005, Ra&uacute;l Mateos 2004-2005.</p>
</div>

<a name="2"><h1>2. Users</h1></a>

<p>The definition of a user is based on the user's
daily activity. One or more profiles can be assigned to a single user</p>

<p>A profile is a list of actions a user can or
cannot perform on a given group, e.g. "view incidents", "database management", etc.</p>

<p>Each user is given a number of groups of agents
he has permission to access, as well as the administrative profile he will have
in each group. Each user can belong to one or more groups, with an assigned
profile for each of them.</p>

<p>Agent belongs to a group and only one, sharing
the group with agents of similar characteristics. Groups also contain
incidents.</p>

<h2><a name="21">2.1. Profile manager</a></h2>

<p>Pandora's profile manager is used to assign specific profiles to each user. A hierarchy of users is so created, structured by the user's profile within the company. With this system different security
levels can be implemented: read-only users, agent group coordinators or system administrators.</p>

<p>A profile is created from the Profile Manager tool in the Administration menu. There are five predefined profiles:</p>

<ul>
<li>Operator (Read)</li>
<li>Operator (Write)</li>
<li>Chief Operator</li>
<li>Group coordinator</li>
<li>Pandora Administrator</li>
</ul>

<p>To create a new profile click on "Manage Profiles"&gt;"Create Profile" in the Administration Menu</p>

<p class="center"><img src="images/image002.png"></p>

<p>Any of the following roles can be assigned to a new profile:</p>

<ul>
<li>View incidents</li>
<li>Edit incidents</li>
<li>View agents. To view agents as well as the events generated by them</li>
<li>Edit agents. To modify then agent's modules</li>
<li>Edit alerts. To modify the alerts assigned to an agent</li>
<li>Manage users. To modify users and their roles</li>
<li>Manage DB. To modify the configuration and data of the database (Global)</li>
<li>Manage alerts. To define new alerts (Global)</li>
<li>Manage Pandora. To modify general system settings</li>
</ul>

<h2><a name="22">2.2. Adding a user</a></h2>

<p>A user is added clicking on "Manage Users"&gt;"Create user" in the Administration Menu</p>

<p>To create a new user it is necessary to, at
least, fill in the user ID, the password (twice) and Pandora's global profile.</p>

<p>A global profile for a user maybe Administrator or Standard User.</p>

<p>A user with an "Administrator" profile will have the highest security privileges in Pandora.</p>

<p class="center"><img src="images/image003.png"></p>

<p>Profiles must be assigned for each of the groups a new "standard" profile user can access, once the user is created and his configuration updated.</p>

<p class="center"><img src="images/image004.png"></p>

<p>A user profile is deleted by clicking on the delete icon <img src="../../images/cancel.gif"> on the right hand side of the profile.</p>

<h2><a name="23">2.3. Deleting a user</a></h2>

<p>A user is deleted by clicking on the delete icon <img src="../../images/cancel.gif"> on the right hand side of the user. The list of users is accessed through the "Manage Users" option in the Administration menu.</p>

<p class="center"><img src="images/image005.png"></p>

<h2><a name="24">2.4. Statistics</a></h2>

<p>The user activity statistics show a graph with the activity of the user, being the number of events the audit has generated for each user. The number of events of
a user usually reflects the user's activity.</p>

<p>Click on "View Users"&gt;"Statistics" in the Operation menu to show this graph:</p>

<p class="center"><img src="images/image006.png"></p>

</body>
</html>