// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('login-text', { text: 'Login' });
    CreateText('url-text', { text: 'Pandora FMS URL' });
    CreateText('password-text', { text: 'Password' });
    CreateText('reportid-text', { text: 'Report ID' });
    CreateGlassButton('done', { onclick: 'showFront', text: 'Done' });
    CreateInfoButton('info', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateButton('refresh', { text: 'Refresh', rightImageWidth: 10, leftImageWidth: 10 });
    CreateText('report_name', {  });
    CreateGauge('gauge-box3', { startAngle: 45, minValue: 100, warningValue: 1, pivotOffsetY: 28, pointerReach: 85, pivotOffsetX: 28, stopAngle: 315, criticalValue: 80 });
    CreateGauge('gauge-box2', { startAngle: 45, minValue: 100, pivotOffsetY: 28, pointerReach: 85, warningValue: 1, pivotOffsetX: 28, stopAngle: 315, criticalValue: 80 });
    CreateGauge('gauge-box1', { startAngle: 45, minValue: 100, warningValue: 1, pivotOffsetY: 28, pointerReach: 85, pivotOffsetX: 28, stopAngle: 315, criticalValue: 80 });
    CreateGauge('gauge-box0', { startAngle: 45, pivotOffsetY: 28, warningValue: 1, pointerReach: 85, minValue: 100, pivotOffsetX: 28, stopAngle: 315, criticalValue: 80 });
    CreateText('agent-text0', { text: 'Agent:' });
    CreateText('agent-text1', { text: 'Agent:' });
    CreateText('agent-text2', { text: 'Agent:' });
    CreateText('agent-text3', { text: 'Agent:' });
    CreateText('agent-value0', {  });
    CreateText('agent-value1', {  });
    CreateText('agent-value2', {  });
    CreateText('agent-value3', {  });
    CreateText('module-value0', {  });
    CreateText('module-text0', { text: 'Module:' });
    CreateText('module-value1', {  });
    CreateText('module-text1', { text: 'Module:' });
    CreateText('module-value2', {  });
    CreateText('module-text2', { text: 'Module:' });
    CreateText('module-value3', {  });
    CreateText('module-text3', { text: 'Module:' });
    CreateText('num-box0', { text: '99' });
    CreateText('num-box1', { text: '99' });
    CreateText('num-box2', { text: '99' });
    CreateText('num-box3', { text: '99' });
}
window.addEventListener('load', setupParts, false);
