#!/bin/sh

# **********************************************************************
# Tentacle Server Daemon launcher for FreeBSD
# (c) 2010 Junichi Satoh <junichi@rworks.jp>
#
# **********************************************************************

# PROVIDE: tentacle_server
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `tentacle_server':
#
# tentacle_server_enable="YES"
#

. "/etc/rc.subr"

name="tentacle_server"
rcvar=`set_rcvar`

# read configuration and set defaults
tentacle_server_enable=${tentacle_server_enable:-"NO"}
tentacle_server_flags=${tentacle_server_flags:-"-a 0.0.0.0 -p 41121 -s /var/spool/pandora/data_in -d"}
tentacle_server_user=${tentacle_server_user:-"pandora"}
load_rc_config $name

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

command=/usr/local/bin/${name}

pidfile=/var/run/$name.pid
start_postcmd=start_postcmd
stop_postcmd=stop_postcmd

procname="/usr/bin/perl"

start_postcmd()
{
	TENTACLE_PID=`ps auxww | grep $command | grep -v grep | head -1 | awk '{ print $2 }'`
	echo $TENTACLE_PID > $pidfile
}

stop_postcmd()
{
	rm -f $pidfile
}

run_rc_command "$1"
