#! /bin/sh
# Copyright (c) 2005-2009 Artica ST
#
# Author: Sancho Lerena <slerena@artica.es> 2006-2009
#
# /etc/init.d/pandora_server
#
# System startup script for Pandora FMS
#
### BEGIN INIT INFO
# Provides:       pandora_server
# Required-Start: $syslog mysql
# Should-Start:   $network 
# Required-Stop:  $syslog mysql
# Should-Stop:    $network mysql
# Default-Start:  2 3 5
# Default-Stop:   0 1 6
# Short-Description: Pandora FMS Server startup script
# Description:    Pandora FMS Server startup script
### END INIT INFO


PANDORA_HOME="/etc/pandora/pandora_server.conf"
PANDORA_PID_PATH="/var/run"
PANDORA_PID=$PANDORA_PID_PATH/pandora_server.pid
PANDORA_DAEMON=/usr/local/bin/pandora_server


# This function replace pidof, not working in the same way in different linux distros

function pidof_pandora () (
	PANDORA_PID=`ps aux | grep "$PANDORA_DAEMON $PANDORA_HOME" | grep -v grep | tail -1 | awk '{ print $2 }'`
	echo $PANDORA_PID
)

# Main script

if [ ! -d "$PANDORA_PID_PATH" ]
then
	echo "Pandora FMS cannot write it's PID file in $PANDORA_PID_PATH. Please create that directory"
	exit
fi

if [ ! -f $PANDORA_DAEMON ]
then
	echo "Pandora FMS Server not found, please check setup and read manual"
	exit
fi

case "$1" in
	start)
		PANDORA_PID=`pidof_pandora`
		if [ ! -z "$PANDORA_PID" ]
		then
			echo "Pandora FMS Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
			exit 1
		fi
	
		$PANDORA_DAEMON $PANDORA_HOME -D
		sleep 2

		PANDORA_PID=`pidof_pandora`
		if [ ! -z "$PANDORA_PID" ]
		then
			echo "Pandora Server is now running with PID $PANDORA_PID"
		else
			echo "Cannot start Pandora FMS Server. Aborted."
			echo "Check Pandora FMS log files at '/var/log/pandora/pandora_server.log'"
		fi
	;;
		
	stop)
		PANDORA_PID=`pidof_pandora`
		if [ -z "$PANDORA_PID" ]
		then
			echo "Pandora FMS Server is not running, cannot stop it."
			exit 1
		else
			echo "Stopping Pandora FMS Server"
			kill $PANDORA_PID > /dev/null 2>&1
		fi
	;;
	status)
		PANDORA_PID=`pidof_pandora`
		if [ -z "$PANDORA_PID" ]
		then
			echo "Pandora FMS Server is not running."
		else
			echo "Pandora FMS Server is running with PID $PANDORA_PID."
		fi
		exit 0
        ;;
  force-reload|restart)
		$0 stop
		sleep 10
		$0 start
		;;
  *)
		echo "Usage: pandora_server { start | stop | restart | status }"
		exit 1
esac

