#!/bin/bash
# Init script for Pandora FMS agent
# Generic GNU/Linux version
# (c) Sancho Lerena, <slerena@gmail.com>
# (c) Evi Vanoost <vanooste@rcbi.rochester.edu> 
# v3.0 

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
PANDORA_PATH=/etc/pandora
DAEMON=/usr/bin/pandora_agent
PIDFILE=/var/run/pandora_agent.pid
LOGFILE=/var/log/pandora_agent.log

if [ ! -f $DAEMON ]
then
	echo "Pandora FMS Agent not found at $DAEMON, please check setup"
	exit
fi

. /etc/rc.common

StartService()
{
        if [ -f $PIDFILE ]
        then
		PID_BA=`cat $PIDFILE`
                if [ ! -z "`ps -A | awk '{ print $1 }' | grep $PID_BA`" ]
                then
                        echo "Pandora FMS Agent is currently running on this machine with PID $PID_BA"
                        echo "Cannot launch again. Aborting."
                        exit
                fi
        fi
	
	$DAEMON $PANDORA_PATH > $LOGFILE 2>&1 & 
    echo $! > $PIDFILE
	echo "Pandora FMS Agent is now running with PID $MYPID"
}

StopService()
{
        if [ -f $PIDFILE ]
        then
			echo "Stopping Pandora Agent."
			PID_BA=`cat $PIDFILE`
			if [ ! -z "`ps -A | grep -v grep | grep 'pandora_agent'`" ]
			then
				kill $PID_BA
			fi
			rm -f $PIDFILE 
        else
			echo "Pandora FMS Agent is not running, cannot stop it. Aborting now..."
        fi
}
 
RestartService()
{
        $0 stop
        $0 start
}

RunService "$1"
