Name:           perl-Net-Traceroute-PurePerl
Version:        0.10
Release:        1%{?dist}
Summary:        Net::Traceroute::PurePerl Perl module
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Traceroute-PurePerl/
Source0:        http://www.cpan.org/authors/id/A/AH/AHOYING/Net-Traceroute-PurePerl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Net::Traceroute) >= 1.05
Requires:       perl(Net::Traceroute) >= 1.05
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module implements traceroute(1) functionality for perl5. It allows you
to trace the path IP packets take to a destination. It is implemented by
using raw sockets to act just like the regular traceroute.

%prep
%setup -q -n Net-Traceroute-PurePerl-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jun 30 2010 Sancho Lerena <slerena@artica.es> 0.10-1
- Specfile autogenerated by cpanspec 1.77.
