Name:           perl-Net-Traceroute
Version:        1.10
Release:        1%{?dist}
Summary:        Traceroute(1) functionality in perl
License:        CHECK(GPL+ or Artistic)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Traceroute/
Source0:        http://www.cpan.org/authors/id/H/HA/HAG/Net-Traceroute-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module implements traceroute(1) functionality for perl5. It allows you
to trace the path IP packets take to a destination. It is currently
implemented as a parser around the system traceroute command.

%prep
%setup -q -n Net-Traceroute-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
#make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jun 30 2010 Sancho Lerena <slerena@artica.es> 1.10-1
- Specfile autogenerated by cpanspec 1.77.
