Name:           perl-Time-Format
Version:        1.11
Release:        1%{?dist}
Summary:        Easy-to-use date/time formatting
License:        CHECK(GPL+ or Artistic)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Time-Format/
Source0:        http://www.cpan.org/authors/id/R/RO/ROODE/Time-Format-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module creates global pseudovariables which format dates and times,
according to formatting codes you pass to them in strings.

%prep
%setup -q -n Time-Format-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes quickref.ps quickref.txt README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jun 30 2010 Sancho Lerena <slerena@artica.es> 1.11-1
- Specfile autogenerated by cpanspec 1.77.
