function insertMenu(n,p) {
document.write("<div id='menu"+n+"' class='"+p+"Menu'><!-- menu "+n+" -->"
+"<div id='label"+n+"1' class='mLabel'>Resources</div>"
+"<div id='box"+n+"1' class='mBox'>"
+"  <a class='m' href='http://sitepoint.com/'>SitePoint</a>"
+"  <a class='m' href='http://sitepointforums.com/'>SitePoint Forums</a>"
+"  <hr>"
+"  <a class='m' href='http://www.hftonline.com/forum/'>HFT Online Forums</a>"
+"  <a class='m' href='http://www.hftonline.com/forum/forumdisplay.php?forumid=16'>HFT Webmastering</a>"
+"  <hr>"
+"  <a class='m' href='http://www.dhtmlcentral.com/'>DHTML Central</a>"
+"  <a class='m' href='http://www.webmasterworld.com/'>Webmaster World</a>"
+"</div>"
+"<div id='label"+n+"2' class='mLabel'>Menus</div>"
+"<div id='box"+n+"2' class='mBox'>"
+"  <a class='m' href='xmenu4_1.html'>xMenu4 Horizontal</a>"
+"  <a class='m' href='xmenu4_2.html'>xMenu4 Vertical</a>"
+"  <a class='m' href='xmenu3_1.html'>xMenu3</a>"
+"  <a class='m' href='xmenu2.html'>xMenu2</a>"
+"</div>"
+"<div id='label"+n+"3' class='mLabel'>Sites</div>"
+"<div id='box"+n+"3' class='mBox'>"
+"  <a class='m' href='http://gonecoastal.net/'>GoneCoastal.net</a>"
+"  <a class='m' href='http://cross-browser.com/'>Cross-Browser.com</a>"
+"  <a class='m' href='http://mfoster.com/'>mFoster.com</a>"
+"  <a class='m' href='http://lineoflight.com/'>LineOfLight.com</a>"
+"  <a class='m' href='http://fosterelectronics.com/'>FosterElectronics.com</a>"
+"  <a class='m' href='http://mitchellfoster.com/'>MitchellFoster.com</a>"
+"  <a class='m' href='http://cross-browser.com/ss/'>Absolute Magnitude</a>"
+"</div>"
+"<div id='label"+n+"4' class='mLabel'>Links</div>"
+"<div id='box"+n+"4' class='mBox'>"
+"  <a class='m' href='http://www.tsalagi.org/'>Tsalagi</a>"
+"  <a class='m' href='http://www.srh.noaa.gov/radar/latest/DS.p37cr/si.kbmx.shtml'>NOAA BMX</a>"
+"  <hr>"
+"  <a class='m' href='http://microcontroller.com/'>MicroController</a>"
+"  <a class='m' href='http://www.programmersheaven.com/'>Programmers Heaven</a>"
+"  <hr>"
+"  <a class='m' href='http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html'>HyperPhysics</a>"
+"  <a class='m' href='http://pegasus.astro.umass.edu/'>2MASS</a>"
+"  <hr>"
+"  <a class='m' href='http://indymedia.org/'>i m c</a>"
+"  <a class='m' href='http://www.csmonitor.com/'>CS Monitor</a>"
+"</div>"


+"</div><!-- end menu"+n+" -->"
); // end document.write()
} // end insertMenu()