#!/bin/bash

# (c) 2008-2009 PandoraFMS.org Development Team
# This script is BSD Licensed.            

# This script is used to copy all received data in /var/spool/pandora/data_in 
# (default Pandora FMS incoming directory) to a remote Tentacle server. 

# Define here your Parameters

TIMEOUT=5
SERVER_IP=192.168.50.1

# Main code, do not alter

while [ 1 ]
do

	for myfile in `find /var/spool/pandora/data_in -type f`
	do
		tentacle_client -q -a $SERVER_IP $myfile
		rm -Rf $myfile

	done
	sleep $TIMEOUT

done
