all: ar.mo  ca.mo  cs.mo  de.mo  el.mo  es.mo  fr.mo  it.mo  ja.mo  nl.mo  pl.mo  pt.mo  pt_BR.mo  ru.mo  sk.mo  tr.mo  zh_CN.mo
	xgettext `find ../../ -name "*\.php"` --from-code=UTF-8 --output=index.pot  --keyword=__ --add-comments=///

ar.mo: ar.po
	msgfmt ar.po -o ar.mo

ast.mo: ast.po
	msgfmt ast.po -o ast.mo

bn.mo: bn.po
	msgfmt bn.po -o bn.mo

ca.mo: ca.po
	msgfmt ca.po -o ca.mo

cs.mo: cs.po
	msgfmt cs.po -o cs.mo

da.mo: da.po
	msgfmt da.po -o da.mo
        
de.mo: de.po
	msgfmt de.po -o de.mo

el.mo: el.po
	msgfmt el.po -o el.mo

es.mo: es.po
	msgfmt es.po -o es.mo

eu.mo: eu.po
	msgfmt eu.po -o eu.mo

fi.mo: fi.po
	msgfmt fi.po -o fi.mo
	
fr.mo: fr.po
	msgfmt fr.po -o fr.mo

gl.mo: gl.po
	msgfmt gl.po -o gl.mo

he.mo: he.po
	msgfmt he.po -o he.mo
	
hi.mo: hi.po
	msgfmt hi.po -o hi.mo
	
hu.mo: hu.po
	msgfmt hu.po -o hu.mo

it.mo: it.po
	msgfmt it.po -o it.mo

ja.mo: ja.po
	msgfmt ja.po -o ja.mo
	
ko.mo: ko.po
	msgfmt ko.po -o ko.mo

nl.mo: nl.po
	msgfmt nl.po -o nl.mo

pl.mo: pl.po
	msgfmt pl.po -o pl.mo
        
pt.mo: pt.po
	msgfmt pt.po -o pt.mo
	
pt_BR.mo: pt_BR.po
	msgfmt pt_BR.po -o pt_BR.mo

ro.mo: ro.po
	msgfmt ro.po -o ro.mo

ru.mo: ru.po
	msgfmt ru.po -o ru.mo  

sk.mo: sk.po
	msgfmt sk.po -o sk.mo

sl.mo: sl.po
	msgfmt sl.po -o sl.mo

sv.mo: sv.po
	msgfmt sv.po -o sv.mo

te.mo: te.po
	msgfmt te.po -o te.mo

tr.mo: tr.po
	msgfmt tr.po -o tr.mo

uk.mo: uk.po
	msgfmt uk.po -o uk.mo

zh_CN.mo: zh_CN.po
	msgfmt zh_CN.po -o zh_CN.mo  

zh_TW.mo: zh_TW.po
	msgfmt zh_TW.po -o zh_TW.mo
